# Generated by Django 3.1.2 on 2020-10-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='degree',
            field=models.IntegerField(default=0),
        ),
    ]
