# Generated by Django 3.1.2 on 2020-10-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20201012_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='status3',
            field=models.BooleanField(default=True),
        ),
    ]
